name: Deploy to Nexus

on:
  push:
    tags:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd easter
          npm install

      - name: Build
        run: |
          cd easter
          npm run build

      - name: Configure npm
        run: echo "//nexus.example.com/repository/npm-repo/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish
        run: |
          cd easter
          npm publish --registry "https://nexus.example.com/repository/npm-repo/"
